---
- name: openjdk platform
  apt: pkg=openjdk-8-jdk,openjdk-8-doc,openjdk-8-source state=latest
  register: installation

- name: gradle build tool
  apt: pkg=gradle,gradle-doc state=latest
  register: installation

- name: apt transport https for sbt repo
  apt: pkg=apt-transport-https state=latest
  register: installation


