---
- name: install software development utilities
  zypper:
    name: ['git', 'git-doc', 'java-11-openjdk-devel', 'java-11-openjdk-javadoc', 'java-11-openjdk-jmods', 'java-11-openjdk-src', 'make']
    state: present
  become: true
