---
- name: install code versioning tools
  pacman:
    name: ['colordiff', 'git', 'chezmoi', 'tmux', 'vim', 'alsa-utils', 'bat', 'exa']
    state: present
  become: true

- name: create git and bat config directories
  file:
    path: "{{ home_dir }}/.config/{{ item }}"
    state: directory
  loop:
    - git
    - bat

- name: create config files for git, vim, tmux
  copy:
    src: "files/{{ item.origin }}"
    dest: "{{ home_dir }}/{{ item.destiny }}"
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
  loop:
    - { origin: git_config, destiny: .config/git/config }
    - { origin: vimrc, destiny: .vimrc }
    - { origin: tmux.conf, destiny: .tmux.conf }
    - { origin: bat_config, destiny: .config/bat/config }

- name: clone tpm tmux plugins
  git:
    repo: https://github.com/tmux-plugins/tpm 
    dest: "{{ home_dir }}/.tmux/plugins/tpm"
    clone: yes
