---
- name: install code versioning tools
  pacman:
    name: ['colordiff', 'git', 'chezmoi', 'tmux', 'vim', 'alsa-utils']
    state: present
  become: true

- name: create git config directory
  file:
    path: "{{ home_dir }}/.config/git"
    state: directory

- name: create git config file
  copy:
    src: files/git_config
    dest: "{{ home_dir }}/.config/git/config"
    owner: "{{ usuario }}"
    group: "{{ grupo }}"

- name: create vi config file
  copy:
    src: files/vimrc
    dest: "{{ home_dir }}/.vimrc"
    owner: "{{ usuario }}"
    group: "{{ grupo }}"

- name: clone tpm tmux plugins
  git:
    repo: https://github.com/tmux-plugins/tpm 
    dest: "{{ home_dir }}/tmux/plugins/tpm"
    clone: yes

- name: create tmux config file
  copy:
    src: files/tmux.conf
    dest: "{{ home_dir }}/.tmux.conf"
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
