# original de opensuse
#background_opacity: 0.4

# parte de mi configuracion nixos
font:
  # Normal (roman) font face
  normal:
    family: Source Code Pro
    # The `style` can be specified to pick a specific face.
    style: Light

  # Bold font face
  bold:
    family: Source Code Pro
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    family: Source Code Pro
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 13.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0


# color schemes https://github.com/jwilm/alacritty/wiki/Color-schemes

# Colors (Nord: https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml)
schemes:
  nord: &nord
    # Default colors
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'

      # Bright and dim foreground colors
      #
      # The dimmed foreground color is calculated automatically if it is not present.
      # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
      # is `false`, the normal foreground color will be used.
      #
      #dim_foreground: '0x9a9a9a'
      #bright_foreground: '0xffffff'

    # Cursor colors
    #
    # These will only be used when the `custom_cursor_colors` field is set to `true`.
    cursor:
      text:    '0x2E3440'
      cursor:  '0xD8DEE9'

    # Normal colors
    normal:
      black:   '0x3B4252'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x88C0D0'
      white:   '0xE5E9F0'

    # Bright colors
    bright:
      black:   '0x4C566A'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x8FBCBB'
      white:   '0xECEFF4'
      
  material: &material
    # Default colors
    primary:
      background: '0x1e282d'
      foreground: '0xc4c7d1'

    # Normal colors
    normal:
      black:   '0x666666'
      red:     '0xeb606b'
      green:   '0xc3e88d'
      yellow:  '0xf7eb95'
      blue:    '0x80cbc4'
      magenta: '0xff2f90'
      cyan:    '0xaeddff'
      white:   '0xffffff'

    # Bright colors
    bright:
      black:   '0xff262b'
      red:     '0xeb606b'
      green:   '0xc3e88d'
      yellow:  '0xf7eb95'
      blue:    '0x7dc6bf'
      magenta: '0x6c71c4'
      cyan:    '0x35434d'
      white:   '0xffffff'

colors: *nord


