---
- name: ssh directory
  file:
    path: "{{ home_dir }}/.ssh"
    state: directory
  tags:
    - base

- name: projects workspace
  file:
    path: "{{ workspace_dir }}/{{ item }}"
    state: directory
  with_items:
    - scala
    - python
    - clojure
    - orgmode
    - github
    - golang
  tags:
    - base

- name: tmp directory
  file:
    path: "{{ temp_dir }}"
    state: directory
  tags:
    - base

- name: apps directory
  file:
    path: "{{ applications_dir }}"
    state: directory
  tags:
    - base

